<?php
echo '<!Doctype html>';
echo '<html lang="en"';
echo '';
echo '<head>';
echo '';
echo '<zym>';
echo '<marquee scrolldelay="5ms" scrollamount="10ms"';
echo 'style="width: 260px;height: 50px;">';
echo '>><i>This is a website</i><<';
echo '</marquee>';
echo '</zym>';
echo '<style>';
echo 'zym {';
echo 'color:red;';
echo 'font-size: 20px;';
echo 'margin-top: 10px;';
echo '}';
echo '</style>';
echo '<title>GROUP10</title>';
echo '<style>';
echo '';
echo 'body {';
echo 'font-family: Arial, sans-serif;';
echo 'background-color: #399bcd;';
echo 'text-align: center;';
echo 'margin: 0;';
echo 'padding: 0;';
echo 'background-image:url('https://haowallpaper.com/link/common/file/previewFileImg/16510977189268864');';
echo 'background-repeat: no-repeat;';
echo 'background-size: cover;';
echo 'background-attachment: fixed;';
echo '';
echo '}';
echo '.container {';
echo 'max-width: 600px;';
echo 'margin: 30px auto;';
echo 'background: rgb(202, 198, 202);';
echo 'padding: 28px;';
echo 'border-radius: 10px;';
echo 'background-image:url('https://haowallpaper.com/link/common/file/previewFileImg/16263609916378496');';
echo 'box-shadow: 20px 20px 20px 10px rgba(0, 0, 0, 0.1);';
echo '}';
echo 'h1 {';
echo 'color: #000000;';
echo '}';
echo 'p {';
echo 'color: #0c0c0c;';
echo 'font-size: 25px;';
echo '}';
echo '.contact {';
echo 'margin-top: 20px;';
echo '}';
echo '.contact a {';
echo 'text-decoration: none;';
echo 'color: #007BFF;';
echo '}';
echo '.profile-pic {';
echo 'width: 200px;';
echo 'height: 200px;';
echo 'border-radius: 50%;';
echo 'object-fit: cover;';
echo 'margin-top: 20px;';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '<div class="container">';
echo '<h1><b>NONAME</b></h1>';
echo '<img src="https://haowallpaper.com/link/common/file/previewFileImg/15964575240342912" alt="picture" class="profile-pic">';
echo '<p><b>EmptyEmptyEmpty</b></p>';
echo '<p><b>Cat</b></p>';
echo '<div class="contact">';
echo '<p><b>404 not found</b></p>';
echo '<p><b>!!!777!!!</b></p>';
echo '<a href="https://wallhaven.cc/search?q=id%3A37&categories=100&purity=100&sorting=random&order=desc&ai_art_filter=1&seed=jNoLpa&page=7"><b>Pictures</b></a>---';
echo '<a href="https://www.youtube.com/"><b>Youtube</b></a>---';
echo '<a href="https://portal.azure.com/#home"><b>Azure</b></a>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</body>';
echo '</html>';
?>